push:
	git commit -am "-AUTO- `date`" || true
	git push || true

download:
	rm -f insert.csv lookup.csv out.png
	scp xiaoxiang@labos2.cs.usyd.edu.au:/mnt/sda/xiaoxiang/RECIPE/P-Masstree/build/insert.csv .
	scp xiaoxiang@labos2.cs.usyd.edu.au:/mnt/sda/xiaoxiang/RECIPE/P-Masstree/build/lookup.csv .
	scp xiaoxiang@labos2.cs.usyd.edu.au:/mnt/sda/xiaoxiang/RECIPE/P-Masstree/build/out.png .
